services:

  comfyui:
    image: mmartial/comfyui-nvidia-docker:ubuntu24_cuda12.8-latest
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8188:8188"
    environment:
      - WANTED_UID=${WANTED_UID:-1000}
      - WANTED_GID=${WANTED_GID:-1000}
      - SECURITY_LEVEL=normal
    volumes:
      - /home/ai/comfyui/run:/comfy/mnt
      - /home/ai/comfyui/basedir:/basedir
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: json-file
      options: { max-size: 10m, max-file: "3" }
